import type { Metadata } from "next";
import { Afacad } from 'next/font/google'
import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

const afacad = Afacad({
  variable: "--afacad",
  weight: ["400", "500", "600", "700"],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${afacad.variable} antialiased`}
      >
        <div className="flex flex-col h-screen">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
